name: Lint

on:
  # push:
  pull_request:
  workflow_call:

concurrency: lint-${{ github.sha }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.9"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}.
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
